# Generated by Django 4.1.3 on 2022-12-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_userrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='skills',
        ),
    ]
